version: '3.9'

services:

  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=app