version: '3.9'

services:

  db:
    image: postgres:13-alpine
    ports:
      - '9999:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=example